name = "kirin"
account_id = "f311d9f5723b811e4d86e1d395701cbf"
workers_dev = true
compatibility_date = "2025-03-15"
main = ".output/server/index.mjs"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

routes = [
    { pattern = "kirin.cldery.com", zone_name = "cldery.com", custom_domain = true }
]
